version: "3"
services:
  speeddating_app:
    build:
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - speeddating_db
    environment:
      - DB_URL="jdbc:postgresql://speeddating_db:5432/test"
      - DB_HOST=speeddating_db
    env_file:
      - .env
  speeddating_db:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - speeddating_db-data:/var/lib/postgresql/data/
volumes:
  speeddating_db-data: null
