version: "3"
services:
  speeddating_app:
    image: nq_speed_dating_web_frontend:0.1-SNAPSHOT
    ports:
      - 3000:8080
    depends_on:
      - speeddating_db
  speeddating_db:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - speeddating_db-data:/var/lib/postgresql/data/
volumes:
  speeddating_db-data:
